import { CommandCategory } from '../types';

export interface CommandDefinition {
  name: string;
  category: CommandCategory;
  description: string;
  usage: string;
  aliases?: string[];
  adminOnly?: boolean;
  groupOnly?: boolean;
  ownerOnly?: boolean;
  generateResponse?: (ctx: any) => string;
}

export const ADDITIONAL_COMMANDS_DATA: CommandDefinition[] = [
  // -------------------------------------------------------------
  // 1. GENERAL & CORE (40 COMMANDS)
  // -------------------------------------------------------------
  { name: 'help', category: 'general', description: 'Show quick help manual and guide', usage: '.help', aliases: ['guide'] },
  { name: 'speed', category: 'general', description: 'Benchmark network and Baileys socket speed', usage: '.speed', aliases: ['latency'] },
  { name: 'runtime', category: 'general', description: 'View current active process running duration', usage: '.runtime', aliases: ['active'] },
  { name: 'creator', category: 'general', description: 'Contact details of bot creator Tyler', usage: '.creator' },
  { name: 'donate', category: 'general', description: 'Support bot server hosting and development', usage: '.donate', aliases: ['tip'] },
  { name: 'report', category: 'general', description: 'Report an issue or bug to Tyler MD developer', usage: '.report <text>' },
  { name: 'rules', category: 'general', description: 'Show official WhatsApp bot rules and policy', usage: '.rules' },
  { name: 'uptime', category: 'general', description: 'Display server and container uptime hours', usage: '.uptime' },
  { name: 'system', category: 'general', description: 'Display full system architecture and OS details', usage: '.system' },
  { name: 'infobot', category: 'general', description: 'Detailed specification of Tyler MD Baileys engine', usage: '.infobot' },
  { name: 'version', category: 'general', description: 'Check Tyler MD software release version', usage: '.version' },
  { name: 'features', category: 'general', description: 'List key standout capabilities of Tyler MD', usage: '.features' },
  { name: 'listonline', category: 'general', description: 'Check online connectivity status', usage: '.listonline' },
  { name: 'checkprefix', category: 'general', description: 'Verify current command prefix trigger', usage: '.checkprefix' },
  { name: 'ping2', category: 'general', description: 'Secondary ICMP round-trip latency probe', usage: '.ping2' },
  { name: 'serverinfo', category: 'general', description: 'Node.js host specs and memory allocation', usage: '.serverinfo' },
  { name: 'changelog', category: 'general', description: 'Read latest updates and patch release notes', usage: '.changelog' },
  { name: 'faq', category: 'general', description: 'Frequently asked questions regarding Tyler MD', usage: '.faq' },
  { name: 'support', category: 'general', description: 'Official Tyler MD community support chat link', usage: '.support' },
  { name: 'credits', category: 'general', description: 'Attributions to Baileys, Whiskeysockets & Tyler', usage: '.credits' },
  { name: 'source', category: 'general', description: 'Open-source repository and code information', usage: '.source' },
  { name: 'feedback', category: 'general', description: 'Send suggestions to bot administration', usage: '.feedback <text>' },
  { name: 'invite', category: 'general', description: 'Invite Tyler MD to your group chat', usage: '.invite' },
  { name: 'joinbot', category: 'general', description: 'Request bot admission into your WhatsApp group', usage: '.joinbot <link>' },
  { name: 'stats', category: 'general', description: 'Global messages processed and command counts', usage: '.stats' },
  { name: 'dashboard', category: 'general', description: 'Web command center dashboard URL and status', usage: '.dashboard' },
  { name: 'database', category: 'general', description: 'Verify local session auth cache integrity', usage: '.database' },
  { name: 'diagnostics', category: 'general', description: 'Run full self-check on all bot subsystems', usage: '.diagnostics' },
  { name: 'ram', category: 'general', description: 'Display Node.js Heap, RSS, and total memory', usage: '.ram' },
  { name: 'cpu', category: 'general', description: 'Display virtual CPU core threads and load', usage: '.cpu' },
  { name: 'storage', category: 'general', description: 'Inspect available disk space for media downloads', usage: '.storage' },
  { name: 'time', category: 'general', description: 'Display current UTC and local synchronized time', usage: '.time' },
  { name: 'date', category: 'general', description: 'Display current calendar date and day', usage: '.date' },
  { name: 'timezone', category: 'general', description: 'Check server time zone offset', usage: '.timezone' },
  { name: 'sessionstatus', category: 'general', description: 'Check Baileys Multi-Device auth state', usage: '.sessionstatus' },
  { name: 'health', category: 'general', description: 'API healthcheck and socket pulse', usage: '.health' },
  { name: 'disclaimer', category: 'general', description: 'Terms of service and privacy disclaimer', usage: '.disclaimer' },
  { name: 'botstatus', category: 'general', description: 'Comprehensive bot status report', usage: '.botstatus' },
  { name: 'terms', category: 'general', description: 'Read user acceptable usage guidelines', usage: '.terms' },
  { name: 'uptime2', category: 'general', description: 'Detailed process runtime since boot', usage: '.uptime2' },

  // -------------------------------------------------------------
  // 2. GROUP MANAGEMENT & ADMINISTRATION (40 COMMANDS)
  // -------------------------------------------------------------
  { name: 'groupopen', category: 'group', description: 'Unmute group so all participants can send messages', usage: '.groupopen', groupOnly: true, adminOnly: true },
  { name: 'groupclose', category: 'group', description: 'Mute group so only admins can send messages', usage: '.groupclose', groupOnly: true, adminOnly: true },
  { name: 'setname', category: 'group', description: 'Change current group chat title', usage: '.setname <new_title>', groupOnly: true, adminOnly: true },
  { name: 'setdesc', category: 'group', description: 'Update group description text', usage: '.setdesc <new_desc>', groupOnly: true, adminOnly: true },
  { name: 'setppgc', category: 'group', description: 'Update group profile photo from replied image', usage: '.setppgc', groupOnly: true, adminOnly: true },
  { name: 'tagme', category: 'group', description: 'Have the bot mention your account in the group', usage: '.tagme', groupOnly: true },
  { name: 'totag', category: 'group', description: 'Re-mention everyone replying to target message', usage: '.totag', groupOnly: true, adminOnly: true },
  { name: 'infogc', category: 'group', description: 'Display group metadata, owner, and creation date', usage: '.infogc', groupOnly: true },
  { name: 'admins', category: 'group', description: 'List all currently appointed administrators', usage: '.admins', groupOnly: true },
  { name: 'gclink', category: 'group', description: 'Retrieve group invite link URL', usage: '.gclink', groupOnly: true },
  { name: 'resetlink', category: 'group', description: 'Revoke and regenerate group invite link', usage: '.resetlink', groupOnly: true, adminOnly: true },
  { name: 'mute', category: 'group', description: 'Quick mute group for members', usage: '.mute', groupOnly: true, adminOnly: true },
  { name: 'unmute', category: 'group', description: 'Quick unmute group for members', usage: '.unmute', groupOnly: true, adminOnly: true },
  { name: 'lockgroup', category: 'group', description: 'Lock group settings from participant edits', usage: '.lockgroup', groupOnly: true, adminOnly: true },
  { name: 'unlockgroup', category: 'group', description: 'Allow participants to modify group info', usage: '.unlockgroup', groupOnly: true, adminOnly: true },
  { name: 'kickall', category: 'group', description: 'Emergency group purge (restricted to owner)', usage: '.kickall', groupOnly: true, ownerOnly: true },
  { name: 'leavegc', category: 'group', description: 'Command bot to exit group', usage: '.leavegc', groupOnly: true, ownerOnly: true },
  { name: 'inviteme', category: 'group', description: 'Send invite link to your private DM', usage: '.inviteme', groupOnly: true },
  { name: 'grouprules', category: 'group', description: 'Display group rules preset', usage: '.grouprules', groupOnly: true },
  { name: 'kickwarned', category: 'group', description: 'Remove all members with 3+ warnings', usage: '.kickwarned', groupOnly: true, adminOnly: true },
  { name: 'grouppoll', category: 'group', description: 'Create group voting poll', usage: '.grouppoll <question>|<opt1>|<opt2>', groupOnly: true },
  { name: 'grouplist', category: 'group', description: 'List participants count and stats', usage: '.grouplist', groupOnly: true },
  { name: 'broadcastgc', category: 'group', description: 'Admin broadcast announcement with banner', usage: '.broadcastgc <text>', groupOnly: true, adminOnly: true },
  { name: 'anticall', category: 'group', description: 'Reject and block automated WhatsApp calls', usage: '.anticall [on|off]', ownerOnly: true },
  { name: 'antispamgc', category: 'group', description: 'Enable aggressive anti-spam in group', usage: '.antispamgc [on|off]', groupOnly: true, adminOnly: true },
  { name: 'resetgclink', category: 'group', description: 'Reset group invite code', usage: '.resetgclink', groupOnly: true, adminOnly: true },
  { name: 'delppgc', category: 'group', description: 'Remove group profile picture', usage: '.delppgc', groupOnly: true, adminOnly: true },
  { name: 'groupid', category: 'group', description: 'Display unique group JID', usage: '.groupid', groupOnly: true },
  { name: 'membercount', category: 'group', description: 'Display total count of participants', usage: '.membercount', groupOnly: true },
  { name: 'admincount', category: 'group', description: 'Display count of active administrators', usage: '.admincount', groupOnly: true },
  { name: 'getdesc', category: 'group', description: 'Fetch group description text', usage: '.getdesc', groupOnly: true },
  { name: 'getppgc', category: 'group', description: 'Download high-res group icon', usage: '.getppgc', groupOnly: true },
  { name: 'checkadmin', category: 'group', description: 'Verify if user holds admin privileges', usage: '.checkadmin', groupOnly: true },
  { name: 'mentionall', category: 'group', description: 'Mention all group participants', usage: '.mentionall <text>', groupOnly: true, adminOnly: true },
  { name: 'pingadmins', category: 'group', description: 'Alert and tag only group administrators', usage: '.pingadmins <text>', groupOnly: true },
  { name: 'gcsettings', category: 'group', description: 'Inspect all active group toggles', usage: '.gcsettings', groupOnly: true },
  { name: 'openchat', category: 'group', description: 'Allow all members to chat', usage: '.openchat', groupOnly: true, adminOnly: true },
  { name: 'closechat', category: 'group', description: 'Restrict chat to administrators', usage: '.closechat', groupOnly: true, adminOnly: true },
  { name: 'poll2', category: 'group', description: 'Create 2-option quick poll', usage: '.poll2 Yes | No', groupOnly: true },
  { name: 'clearwarns', category: 'group', description: 'Clear warnings for all group members', usage: '.clearwarns', groupOnly: true, adminOnly: true },

  // -------------------------------------------------------------
  // 3. MODERATION & WARN SYSTEM (35 COMMANDS)
  // -------------------------------------------------------------
  { name: 'warn1', category: 'moderation', description: 'Add 1 warning strike to participant', usage: '.warn1 @user', groupOnly: true, adminOnly: true },
  { name: 'warn2', category: 'moderation', description: 'Add 2 warning strikes to participant', usage: '.warn2 @user', groupOnly: true, adminOnly: true },
  { name: 'unwarnall', category: 'moderation', description: 'Clear all strikes for member', usage: '.unwarnall @user', groupOnly: true, adminOnly: true },
  { name: 'warncheck', category: 'moderation', description: 'Check warning count of @user', usage: '.warncheck @user', groupOnly: true },
  { name: 'setwarnlimit', category: 'moderation', description: 'Set maximum warnings before auto-kick', usage: '.setwarnlimit 3', groupOnly: true, adminOnly: true },
  { name: 'banuser', category: 'moderation', description: 'Permanently blacklist user from group', usage: '.banuser @user', groupOnly: true, adminOnly: true },
  { name: 'unbanuser', category: 'moderation', description: 'Remove user from group blacklist', usage: '.unbanuser @user', groupOnly: true, adminOnly: true },
  { name: 'mutemember', category: 'moderation', description: 'Delete all messages sent by target user', usage: '.mutemember @user', groupOnly: true, adminOnly: true },
  { name: 'unmutemember', category: 'moderation', description: 'Restore user chat permissions', usage: '.unmutemember @user', groupOnly: true, adminOnly: true },
  { name: 'badwords', category: 'moderation', description: 'List active prohibited words', usage: '.badwords', groupOnly: true },
  { name: 'addbadword', category: 'moderation', description: 'Add forbidden word to toxicity filter', usage: '.addbadword <word>', groupOnly: true, adminOnly: true },
  { name: 'delbadword', category: 'moderation', description: 'Remove word from toxicity filter', usage: '.delbadword <word>', groupOnly: true, adminOnly: true },
  { name: 'slowmode', category: 'moderation', description: 'Set chat message delay per user', usage: '.slowmode 10s', groupOnly: true, adminOnly: true },
  { name: 'antispamlevel', category: 'moderation', description: 'Adjust anti-spam sensitivity', usage: '.antispamlevel high', groupOnly: true, adminOnly: true },
  { name: 'purge', category: 'moderation', description: 'Purge last N messages in group', usage: '.purge 10', groupOnly: true, adminOnly: true },
  { name: 'antilinkmode', category: 'moderation', description: 'Set anti-link reaction (delete|warn|kick)', usage: '.antilinkmode kick', groupOnly: true, adminOnly: true },
  { name: 'blacklistadd', category: 'moderation', description: 'Add phone number to global ban list', usage: '.blacklistadd <number>', ownerOnly: true },
  { name: 'blacklistdel', category: 'moderation', description: 'Remove phone number from global ban list', usage: '.blacklistdel <number>', ownerOnly: true },
  { name: 'blacklistview', category: 'moderation', description: 'View all blacklisted numbers', usage: '.blacklistview', ownerOnly: true },
  { name: 'kickghosts', category: 'moderation', description: 'Kick inactive participants with zero messages', usage: '.kickghosts', groupOnly: true, adminOnly: true },
  { name: 'whitelistadd', category: 'moderation', description: 'Exempt user from anti-link & anti-spam', usage: '.whitelistadd @user', groupOnly: true, adminOnly: true },
  { name: 'whitelistdel', category: 'moderation', description: 'Remove user from whitelist exemption', usage: '.whitelistdel @user', groupOnly: true, adminOnly: true },
  { name: 'antitagall', category: 'moderation', description: 'Block non-admins from running mass mentions', usage: '.antitagall on/off', groupOnly: true, adminOnly: true },
  { name: 'antiraid', category: 'moderation', description: 'Lock group against rapid join floods', usage: '.antiraid on/off', groupOnly: true, adminOnly: true },
  { name: 'automute', category: 'moderation', description: 'Automatically mute group at night hours', usage: '.automute 22:00', groupOnly: true, adminOnly: true },
  { name: 'autounmute', category: 'moderation', description: 'Automatically open group in the morning', usage: '.autounmute 07:00', groupOnly: true, adminOnly: true },
  { name: 'warnreset', category: 'moderation', description: 'Reset user strikes to zero', usage: '.warnreset @user', groupOnly: true, adminOnly: true },
  { name: 'modlog', category: 'moderation', description: 'View log of recent kicks and warns', usage: '.modlog', groupOnly: true, adminOnly: true },
  { name: 'antiviewonce', category: 'moderation', description: 'Forward view-once media to owner', usage: '.antiviewonce on/off', ownerOnly: true },
  { name: 'reportmember', category: 'moderation', description: 'File anonymous report to group admins', usage: '.reportmember @user <reason>', groupOnly: true },
  { name: 'clearchatlog', category: 'moderation', description: 'Flush moderation history', usage: '.clearchatlog', groupOnly: true, adminOnly: true },
  { name: 'antispamwarn', category: 'moderation', description: 'Warn flooders automatically', usage: '.antispamwarn on/off', groupOnly: true, adminOnly: true },
  { name: 'filterlinks', category: 'moderation', description: 'Scan recent group messages for links', usage: '.filterlinks', groupOnly: true, adminOnly: true },
  { name: 'checkthreat', category: 'moderation', description: 'Scan user profile for bug payload signs', usage: '.checkthreat @user', groupOnly: true },
  { name: 'guardstatus', category: 'moderation', description: 'Inspect active moderation defenses', usage: '.guardstatus', groupOnly: true },

  // -------------------------------------------------------------
  // 4. SECURITY & BUG BOT DEFENSES (35 COMMANDS)
  // -------------------------------------------------------------
  { name: 'deepscan', category: 'security', description: 'Deep scan chat history for hidden bug codes', usage: '.deepscan' },
  { name: 'bugshield', category: 'security', description: 'Nexus / Queen Lavita real-time crash shield', usage: '.bugshield on/off', ownerOnly: true },
  { name: 'bidi-protect', category: 'security', description: 'Neutralize Unicode RTL BiDi renderer crasher', usage: '.bidi-protect on/off', ownerOnly: true },
  { name: 'zerowidth-filter', category: 'security', description: 'Strip invisible zero-width character bombs', usage: '.zerowidth-filter on/off', ownerOnly: true },
  { name: 'vcard-guard', category: 'security', description: 'Prevent oversized corrupted vCard attacks', usage: '.vcard-guard on/off', ownerOnly: true },
  { name: 'crashshield', category: 'security', description: 'Maximum crash defense protocol status', usage: '.crashshield', ownerOnly: true },
  { name: 'packetfilter', category: 'security', description: 'Filter malformed Baileys protocol stanzas', usage: '.packetfilter on/off', ownerOnly: true },
  { name: 'ratelimit', category: 'security', description: 'Enforce 5 msgs/4s threshold per sender', usage: '.ratelimit [on|off]', ownerOnly: true },
  { name: 'antibot', category: 'security', description: 'Detect and auto-kick unauthorized spam bots', usage: '.antibot on/off', groupOnly: true, adminOnly: true },
  { name: 'antifake', category: 'security', description: 'Block virtual numbers (e.g. +1, +48, +994)', usage: '.antifake on/off', groupOnly: true, adminOnly: true },
  { name: 'blockcountry', category: 'security', description: 'Prohibit foreign international country codes', usage: '.blockcountry <code_prefix>', groupOnly: true, adminOnly: true },
  { name: 'shieldstatus', category: 'security', description: 'Full report of all active security filters', usage: '.shieldstatus' },
  { name: 'threatlog', category: 'security', description: 'View blocked crash payloads and timestamps', usage: '.threatlog', ownerOnly: true },
  { name: 'clearthreats', category: 'security', description: 'Flush recorded security threat incidents', usage: '.clearthreats', ownerOnly: true },
  { name: 'quarantine', category: 'security', description: 'Isolate suspicious participant session', usage: '.quarantine @user', ownerOnly: true },
  { name: 'auditlog', category: 'security', description: 'Generate security audit report', usage: '.auditlog', ownerOnly: true },
  { name: 'securitymatrix', category: 'security', description: 'Display Tyler MD defense grid levels', usage: '.securitymatrix' },
  { name: 'killswitch', category: 'security', description: 'Emergency shutdown of all incoming parsing', usage: '.killswitch', ownerOnly: true },
  { name: 'lockdown', category: 'security', description: 'Initiate group emergency lockdown', usage: '.lockdown', groupOnly: true, adminOnly: true },
  { name: 'firewall', category: 'security', description: 'Enable Baileys protocol firewall', usage: '.firewall on/off', ownerOnly: true },
  { name: 'packetdrop', category: 'security', description: 'Drop oversized incoming message packets', usage: '.packetdrop', ownerOnly: true },
  { name: 'antiinvite', category: 'security', description: 'Block all WhatsApp community invites', usage: '.antiinvite on/off', groupOnly: true, adminOnly: true },
  { name: 'antinsfw', category: 'security', description: 'Detect and delete explicit image media', usage: '.antinsfw on/off', groupOnly: true, adminOnly: true },
  { name: 'antiporn', category: 'security', description: 'Activate AI image content safety filter', usage: '.antiporn on/off', groupOnly: true, adminOnly: true },
  { name: 'inspectpayload', category: 'security', description: 'Analyze quoted message for crash bytes', usage: '.inspectpayload' },
  { name: 'safemode', category: 'security', description: 'Enable strict hardened operational mode', usage: '.safemode on/off', ownerOnly: true },
  { name: 'sanitize', category: 'security', description: 'Sanitize group description and chat titles', usage: '.sanitize', groupOnly: true, adminOnly: true },
  { name: 'antitraps', category: 'security', description: 'Prevent link preview traps and IP loggers', usage: '.antitraps on/off', ownerOnly: true },
  { name: 'clearmalware', category: 'security', description: 'Purge cached media files from memory', usage: '.clearmalware', ownerOnly: true },
  { name: 'integritycheck', category: 'security', description: 'Check Baileys auth credentials hash', usage: '.integritycheck', ownerOnly: true },
  { name: 'threatcount', category: 'security', description: 'Total count of neutralized exploits', usage: '.threatcount' },
  { name: 'defensemode', category: 'security', description: 'Switch between Relaxed / Standard / Paranoid', usage: '.defensemode paranoid', ownerOnly: true },
  { name: 'dropbomb', category: 'security', description: 'Simulate and verify crash code neutralization', usage: '.dropbomb' },
  { name: 'blocklistgc', category: 'security', description: 'List of banned numbers in current group', usage: '.blocklistgc', groupOnly: true },
  { name: 'verifyarmor', category: 'security', description: 'Run test handshake against bug filter', usage: '.verifyarmor' },

  // -------------------------------------------------------------
  // 5. AUTOMATION, PRESENCE & RESPONDERS (30 COMMANDS)
  // -------------------------------------------------------------
  { name: 'autoreply', category: 'autoreply', description: 'List all active automated reply triggers', usage: '.autoreply' },
  { name: 'autoreplyadd', category: 'autoreply', description: 'Add new keyword auto-responder', usage: '.autoreplyadd <trigger>|<response>', ownerOnly: true },
  { name: 'autoreplydel', category: 'autoreply', description: 'Delete existing auto-responder rule', usage: '.autoreplydel <id>', ownerOnly: true },
  { name: 'autoreplylist', category: 'autoreply', description: 'Inspect configured reply mappings', usage: '.autoreplylist' },
  { name: 'autoreplyclear', category: 'autoreply', description: 'Clear custom automated rules', usage: '.autoreplyclear', ownerOnly: true },
  { name: 'autoonline', category: 'autoreply', description: 'Keep bot presence marked permanently online', usage: '.autoonline on/off', ownerOnly: true },
  { name: 'autobio', category: 'autoreply', description: 'Update WhatsApp bio with live bot uptime', usage: '.autobio on/off', ownerOnly: true },
  { name: 'autorejectcall', category: 'autoreply', description: 'Auto-decline incoming calls with explanation', usage: '.autorejectcall on/off', ownerOnly: true },
  { name: 'autosavecontact', category: 'autoreply', description: 'Auto-register new sender contact', usage: '.autosavecontact on/off', ownerOnly: true },
  { name: 'autoviewstatus', category: 'autoreply', description: 'Automatically view and read contact WhatsApp statuses', usage: '.autoviewstatus on/off', ownerOnly: true },
  { name: 'autolike', category: 'autoreply', description: 'Auto-like viewed status updates with reaction', usage: '.autolike on/off', ownerOnly: true },
  { name: 'autowelcome', category: 'autoreply', description: 'Toggle automated participant welcome banner', usage: '.autowelcome on/off', groupOnly: true, adminOnly: true },
  { name: 'autogoodbye', category: 'autoreply', description: 'Toggle automated participant exit notice', usage: '.autogoodbye on/off', groupOnly: true, adminOnly: true },
  { name: 'welcomemsg', category: 'autoreply', description: 'Customize group welcome template', usage: '.welcomemsg <template>', groupOnly: true, adminOnly: true },
  { name: 'goodbyemsg', category: 'autoreply', description: 'Customize group goodbye template', usage: '.goodbyemsg <template>', groupOnly: true, adminOnly: true },
  { name: 'autosticker', category: 'autoreply', description: 'Automatically convert sent images to stickers', usage: '.autosticker on/off', groupOnly: true, adminOnly: true },
  { name: 'autotranslate', category: 'autoreply', description: 'Auto-translate incoming foreign chat messages', usage: '.autotranslate [es|fr|de]', groupOnly: true },
  { name: 'delayreply', category: 'autoreply', description: 'Set simulated human response delay in milliseconds', usage: '.delayreply 500', ownerOnly: true },
  { name: 'filterkeyword', category: 'autoreply', description: 'Match specific keyword trigger', usage: '.filterkeyword <word>' },
  { name: 'presencecomposing', category: 'autoreply', description: 'Set bot status to "typing..."', usage: '.presencecomposing', ownerOnly: true },
  { name: 'presencerecording', category: 'autoreply', description: 'Set bot status to "recording audio..."', usage: '.presencerecording', ownerOnly: true },
  { name: 'presencepaused', category: 'autoreply', description: 'Set bot status to idle', usage: '.presencepaused', ownerOnly: true },
  { name: 'presencereset', category: 'autoreply', description: 'Reset WhatsApp presence to default', usage: '.presencereset', ownerOnly: true },
  { name: 'schedulemsg', category: 'autoreply', description: 'Schedule timed WhatsApp message delivery', usage: '.schedulemsg 10m <text>' },
  { name: 'reminder', category: 'autoreply', description: 'Set personal reminder alert with timer', usage: '.reminder 30m Take medicine' },
  { name: 'autoblue', category: 'autoreply', description: 'Toggle blue double ticks on receive', usage: '.autoblue on/off', ownerOnly: true },
  { name: 'autoreactemoji', category: 'autoreply', description: 'Change automatic reaction emoji', usage: '.autoreactemoji 🔥', ownerOnly: true },
  { name: 'responderstatus', category: 'autoreply', description: 'View status of all automated workers', usage: '.responderstatus' },
  { name: 'testautoreply', category: 'autoreply', description: 'Test custom auto-reply match', usage: '.testautoreply <query>' },
  { name: 'clearautomation', category: 'autoreply', description: 'Reset all automation parameters', usage: '.clearautomation', ownerOnly: true },

  // -------------------------------------------------------------
  // 6. AI & GEMINI INTELLIGENCE STUDIO (35 COMMANDS)
  // -------------------------------------------------------------
  { name: 'gpt', category: 'ai', description: 'Chat with Gemini 2.5 Flash intelligent engine', usage: '.gpt <query>', aliases: ['chatgpt'] },
  { name: 'ask', category: 'ai', description: 'Ask question with concise, factual response', usage: '.ask <question>' },
  { name: 'grammar', category: 'ai', description: 'Fix grammar, spelling and punctuation errors', usage: '.grammar <text>' },
  { name: 'code', category: 'ai', description: 'Generate software code snippet in any language', usage: '.code <language> <prompt>' },
  { name: 'explain', category: 'ai', description: 'Explain complex concepts in simple terms', usage: '.explain <concept>' },
  { name: 'write', category: 'ai', description: 'Write formal email, message or letter', usage: '.write <subject>' },
  { name: 'poem', category: 'ai', description: 'Generate poetic verses on requested theme', usage: '.poem <topic>' },
  { name: 'essay', category: 'ai', description: 'Generate structured academic essay draft', usage: '.essay <topic>' },
  { name: 'story', category: 'ai', description: 'Generate engaging short story', usage: '.story <plot>' },
  { name: 'lyrics', category: 'ai', description: 'Generate song lyrics with verse and chorus', usage: '.lyrics <genre> <topic>' },
  { name: 'joke', category: 'ai', description: 'Generate funny programmer or dad joke', usage: '.joke' },
  { name: 'riddle', category: 'ai', description: 'Generate brain-teaser riddle with hidden answer', usage: '.riddle' },
  { name: 'quote', category: 'ai', description: 'Generate profound philosophical quote', usage: '.quote' },
  { name: 'philosophize', category: 'ai', description: 'Explore existential thought experiment', usage: '.philosophize <topic>' },
  { name: 'mathsolver', category: 'ai', description: 'Solve advanced calculus, algebra or math problem', usage: '.mathsolver <equation>' },
  { name: 'regexgen', category: 'ai', description: 'Generate Regular Expression from description', usage: '.regexgen <pattern_desc>' },
  { name: 'sqlexplain', category: 'ai', description: 'Generate or explain PostgreSQL / SQL query', usage: '.sqlexplain <query>' },
  { name: 'gitcommitgen', category: 'ai', description: 'Generate conventional Git commit message', usage: '.gitcommitgen <diff_or_summary>' },
  { name: 'debugcode', category: 'ai', description: 'Analyze code snippet for logical bugs', usage: '.debugcode <code>' },
  { name: 'aiimageprompt', category: 'ai', description: 'Generate high-fidelity Midjourney/Gemini prompt', usage: '.aiimageprompt <idea>' },
  { name: 'sentiment', category: 'ai', description: 'Analyze emotional sentiment of text', usage: '.sentiment <text>' },
  { name: 'keywordextract', category: 'ai', description: 'Extract primary keywords and topics from text', usage: '.keywordextract <text>' },
  { name: 'paraphrase', category: 'ai', description: 'Rewrite text with fresh vocabulary', usage: '.paraphrase <text>' },
  { name: 'bulletpoints', category: 'ai', description: 'Convert wall of text into digestible bullets', usage: '.bulletpoints <text>' },
  { name: 'eli5', category: 'ai', description: 'Explain Like I\'m 5 years old', usage: '.eli5 <topic>' },
  { name: 'tldr', category: 'ai', description: 'Provide ultra-short summary of text', usage: '.tldr <text>' },
  { name: 'factcheck', category: 'ai', description: 'Verify accuracy of a claim or statement', usage: '.factcheck <statement>' },
  { name: 'aichat', category: 'ai', description: 'Interactive conversational chat turn', usage: '.aichat <message>' },
  { name: 'interviewprep', category: 'ai', description: 'Practice technical interview questions', usage: '.interviewprep <job_role>' },
  { name: 'roastme', category: 'ai', description: 'Playful humorous roast from Tyler MD', usage: '.roastme' },
  { name: 'compliment', category: 'ai', description: 'Receive uplifting customized compliment', usage: '.compliment' },
  { name: 'synonym', category: 'ai', description: 'Find rich synonyms and antonyms', usage: '.synonym <word>' },
  { name: 'proverb', category: 'ai', description: 'Share ancient cultural proverb and meaning', usage: '.proverb' },
  { name: 'businessidea', category: 'ai', description: 'Generate innovative startup concept', usage: '.businessidea <niche>' },
  { name: 'haiku', category: 'ai', description: 'Write 5-7-5 syllable Japanese haiku poem', usage: '.haiku <topic>' },

  // -------------------------------------------------------------
  // 7. MEDIA DOWNLOADERS & CONVERTERS (35 COMMANDS)
  // -------------------------------------------------------------
  { name: 'tiktokmp3', category: 'media', description: 'Extract audio MP3 track from TikTok video', usage: '.tiktokmp3 <url>' },
  { name: 'ytmp3', category: 'media', description: 'Download YouTube video as 320kbps MP3', usage: '.ytmp3 <url>' },
  { name: 'ytmp4', category: 'media', description: 'Download YouTube video as 720p/1080p MP4', usage: '.ytmp4 <url>' },
  { name: 'ytsearch', category: 'media', description: 'Search YouTube videos with thumbnail previews', usage: '.ytsearch <query>' },
  { name: 'igreel', category: 'media', description: 'Download Instagram Reel video', usage: '.igreel <url>' },
  { name: 'igstory', category: 'media', description: 'Download Instagram User Story update', usage: '.igstory <username>' },
  { name: 'igpost', category: 'media', description: 'Download Instagram photo carousel post', usage: '.igpost <url>' },
  { name: 'xdown', category: 'media', description: 'Download Twitter / X video at 60 FPS', usage: '.xdown <tweet_url>' },
  { name: 'facebook', category: 'media', description: 'Download Facebook watch / reel video', usage: '.facebook <fb_url>', aliases: ['fb'] },
  { name: 'fbdown', category: 'media', description: 'Extract HD video from Facebook link', usage: '.fbdown <url>' },
  { name: 'spotify', category: 'media', description: 'Download track info & preview from Spotify', usage: '.spotify <track_url_or_query>' },
  { name: 'soundcloud', category: 'media', description: 'Download music from SoundCloud stream', usage: '.soundcloud <url>' },
  { name: 'pinterest', category: 'media', description: 'Download high-res aesthetic image from Pinterest', usage: '.pinterest <query>' },
  { name: 'threads', category: 'media', description: 'Download video or image from Meta Threads', usage: '.threads <url>' },
  { name: 'snapchat', category: 'media', description: 'Download public Snapchat Spotlight video', usage: '.snapchat <url>' },
  { name: 'mediafire', category: 'media', description: 'Download file directly from Mediafire URL', usage: '.mediafire <url>' },
  { name: 'gdrive', category: 'media', description: 'Download shared file from Google Drive', usage: '.gdrive <url>' },
  { name: 'apkdl', category: 'media', description: 'Download Android APK package by package name', usage: '.apkdl <app_name>' },
  { name: 'gitclone', category: 'media', description: 'Download public GitHub repo as ZIP file', usage: '.gitclone <repo_url>' },
  { name: 'play', category: 'media', description: 'Search and instantly play music audio', usage: '.play <song_name>' },
  { name: 'song', category: 'media', description: 'Download full audio track by title', usage: '.song <name>' },
  { name: 'video', category: 'media', description: 'Download video clip by title search', usage: '.video <title>' },
  { name: 'lyricsfinder', category: 'media', description: 'Search full song lyrics and artist info', usage: '.lyricsfinder <song>' },
  { name: 'shazam', category: 'media', description: 'Identify song title from voice note / audio reply', usage: '.shazam' },
  { name: 'findmusic', category: 'media', description: 'Recognize song melody and soundtrack', usage: '.findmusic' },
  { name: 'toimg', category: 'media', description: 'Convert WhatsApp sticker to JPEG/PNG image', usage: '.toimg' },
  { name: 'tovideo', category: 'media', description: 'Convert animated sticker into MP4 video', usage: '.tovideo' },
  { name: 'toaudio', category: 'media', description: 'Extract audio track from video clip', usage: '.toaudio' },
  { name: 'tomp3', category: 'media', description: 'Convert voice note to standard MP3 file', usage: '.tomp3' },
  { name: 'compressmedia', category: 'media', description: 'Compress video file to fit WhatsApp size limits', usage: '.compressmedia' },
  { name: 'reverseimg', category: 'media', description: 'Reverse image search on Google Images', usage: '.reverseimg' },
  { name: 'downloadimg', category: 'media', description: 'Download web image from URL link', usage: '.downloadimg <url>' },
  { name: 'mediawhois', category: 'media', description: 'Inspect EXIF metadata of quoted image', usage: '.mediawhois' },
  { name: 'mediastats', category: 'media', description: 'Check resolution, bitrate and codecs of media', usage: '.mediastats' },
  { name: 'trimvideo', category: 'media', description: 'Trim video clip duration by start and end seconds', usage: '.trimvideo 0:10 0:30' },

  // -------------------------------------------------------------
  // 8. STICKERS & IMAGE STUDIO (35 COMMANDS)
  // -------------------------------------------------------------
  { name: 's', category: 'stickers', description: 'Fast shortcut to create WhatsApp sticker', usage: '.s (reply to media)' },
  { name: 'take', category: 'stickers', description: 'Rebrand sticker pack and author attribution', usage: '.take Pack | Tyler MD' },
  { name: 'wm', category: 'stickers', description: 'Apply custom watermark metadata to sticker', usage: '.wm Tyler | MD' },
  { name: 'emojimix', category: 'stickers', description: 'Combine two emojis into single sticker (e.g. 🐱+🚀)', usage: '.emojimix 🐱 🚀' },
  { name: 'qc', category: 'stickers', description: 'Generate WhatsApp chat bubble quote sticker', usage: '.qc <quote_text>' },
  { name: 'quotely', category: 'stickers', description: 'Create verified styled quote image', usage: '.quotely <text>' },
  { name: 'attp', category: 'stickers', description: 'Animated rainbow text sticker generator', usage: '.attp <text>' },
  { name: 'ttp', category: 'stickers', description: 'Plain text to sticker generator', usage: '.ttp <text>' },
  { name: 'circle', category: 'stickers', description: 'Crop image into circular sticker', usage: '.circle' },
  { name: 'wasted', category: 'stickers', description: 'Apply GTA Wasted overlay effect to photo', usage: '.wasted' },
  { name: 'triggered', category: 'stickers', description: 'Generate vibrating TRIGGERED animated GIF', usage: '.triggered' },
  { name: 'blur', category: 'stickers', description: 'Apply privacy blur filter to image', usage: '.blur [1-10]' },
  { name: 'grayscale', category: 'stickers', description: 'Convert photo to classic monochrome black & white', usage: '.grayscale' },
  { name: 'invert', category: 'stickers', description: 'Invert image colors into negative spectrum', usage: '.invert' },
  { name: 'sepia', category: 'stickers', description: 'Apply warm vintage sepia tone filter', usage: '.sepia' },
  { name: 'meme', category: 'stickers', description: 'Generate meme image with top and bottom captions', usage: '.meme Top Text | Bottom Text' },
  { name: 'pixelate', category: 'stickers', description: 'Pixelate image with 8-bit retro gaming look', usage: '.pixelate' },
  { name: 'sharpen', category: 'stickers', description: 'Enhance image edges and sharpness', usage: '.sharpen' },
  { name: 'glitch', category: 'stickers', description: 'Apply cyberpunk VHS glitch distortion to photo', usage: '.glitch' },
  { name: 'mirror', category: 'stickers', description: 'Mirror image horizontally or vertically', usage: '.mirror' },
  { name: 'removebg', category: 'stickers', description: 'Remove background from photo (AI transparent PNG)', usage: '.removebg' },
  { name: 'stickergif', category: 'stickers', description: 'Convert video/GIF into animated WhatsApp sticker', usage: '.stickergif' },
  { name: 'stickertelegram', category: 'stickers', description: 'Import full sticker set from Telegram link', usage: '.stickertelegram <t.me/addstickers/...>' },
  { name: 'animesticker', category: 'stickers', description: 'Generate random high-quality anime sticker', usage: '.animesticker' },
  { name: 'memesticker', category: 'stickers', description: 'Generate viral meme sticker', usage: '.memesticker' },
  { name: 'brat', category: 'stickers', description: 'Generate trending Charli XCX Brat style sticker', usage: '.brat <text>' },
  { name: 'smeme', category: 'stickers', description: 'Create sticker meme with text overlays', usage: '.smeme top|bottom' },
  { name: 'snobg', category: 'stickers', description: 'Convert sticker removing background automatically', usage: '.snobg' },
  { name: 'stickermeta', category: 'stickers', description: 'Inspect raw EXIF metadata tags of sticker', usage: '.stickermeta' },
  { name: 'roundsticker', category: 'stickers', description: 'Crop media into round sticker format', usage: '.roundsticker' },
  { name: 'flip', category: 'stickers', description: 'Flip image upside down', usage: '.flip' },
  { name: 'contrast', category: 'stickers', description: 'Boost photo contrast by 30%', usage: '.contrast' },
  { name: 'vintage', category: 'stickers', description: 'Apply retro 90s film aesthetic', usage: '.vintage' },
  { name: 'drip', category: 'stickers', description: 'Add comic drip art border to portrait', usage: '.drip' },
  { name: 'comic', category: 'stickers', description: 'Convert photo to halftone comic book print', usage: '.comic' },

  // -------------------------------------------------------------
  // 9. FUN, ANIME, GAMES & ROLEPLAY (45 COMMANDS)
  // -------------------------------------------------------------
  { name: 'anime', category: 'anime', description: 'Fetch high resolution anime wallpaper art', usage: '.anime [character_or_title]' },
  { name: 'waifu', category: 'anime', description: 'Generate beautiful random anime waifu portrait', usage: '.waifu' },
  { name: 'neko', category: 'anime', description: 'Fetch cute anime catgirl (neko) art illustration', usage: '.neko' },
  { name: 'husbando', category: 'anime', description: 'Fetch random handsome anime husbando artwork', usage: '.husbando' },
  { name: 'shinobu', category: 'anime', description: 'Fetch Demon Slayer Shinobu Kocho art image', usage: '.shinobu' },
  { name: 'megumin', category: 'anime', description: 'Fetch Konosuba Megumin explosion art', usage: '.megumin' },
  { name: 'kiss', category: 'anime', description: 'Send romantic anime kiss reaction GIF to @user', usage: '.kiss @user' },
  { name: 'hug', category: 'anime', description: 'Send warm anime hug embrace to @user', usage: '.hug @user' },
  { name: 'pat', category: 'anime', description: 'Gently headpat @user with anime reaction', usage: '.pat @user' },
  { name: 'slap', category: 'anime', description: 'Playfully slap @user with anime reaction', usage: '.slap @user' },
  { name: 'punch', category: 'anime', description: 'Send dynamic anime punch attack to @user', usage: '.punch @user' },
  { name: 'cuddle', category: 'anime', description: 'Cuddle with @user in chat', usage: '.cuddle @user' },
  { name: 'cry', category: 'anime', description: 'Express anime tears and sadness in chat', usage: '.cry' },
  { name: 'dance', category: 'anime', description: 'Vibe and dance with energetic anime moves', usage: '.dance' },
  { name: 'smile', category: 'anime', description: 'Radiate wholesome anime happiness', usage: '.smile' },
  { name: 'wink', category: 'anime', description: 'Give charming anime wink to chat', usage: '.wink' },
  { name: 'blush', category: 'anime', description: 'Get flustered and blush with anime emotion', usage: '.blush' },
  { name: 'bonk', category: 'anime', description: 'Send @user to horny jail with squeaky bonk', usage: '.bonk @user' },
  { name: 'yeet', category: 'anime', description: 'Yeet @user across the stratosphere', usage: '.yeet @user' },
  { name: 'poke', category: 'anime', description: 'Playfully poke @user to get attention', usage: '.poke @user' },
  { name: 'kill', category: 'anime', description: 'Dramatic anime finishing move on @user', usage: '.kill @user' },
  { name: 'ship', category: 'anime', description: 'Calculate romantic compatibility between two users', usage: '.ship @user1 @user2' },
  { name: 'lovecalc', category: 'anime', description: 'Calculate love score percentage', usage: '.lovecalc @user' },
  { name: 'simprate', category: 'anime', description: 'Measure simp meter percentage of target user', usage: '.simprate @user' },
  { name: 'gayrate', category: 'anime', description: 'Humorous rainbow meter scanner', usage: '.gayrate @user' },
  { name: 'coolrate', category: 'anime', description: 'Calculate aura and coolness score / 100', usage: '.coolrate @user' },
  { name: 'truth', category: 'anime', description: 'Get provocative Truth question for party game', usage: '.truth' },
  { name: 'dare', category: 'anime', description: 'Get daring challenge for WhatsApp games', usage: '.dare' },
  { name: 'coinflip', category: 'anime', description: 'Flip virtual silver coin (Heads or Tails)', usage: '.coinflip' },
  { name: 'roll', category: 'anime', description: 'Roll D6 / D20 dice with random roll result', usage: '.roll [d6|d20]' },
  { name: 'dice', category: 'anime', description: 'Roll two six-sided casino dice', usage: '.dice' },
  { name: '8ball', category: 'anime', description: 'Ask the mystical Magic 8-Ball your destiny', usage: '.8ball <question>' },
  { name: 'trivia', category: 'anime', description: 'General knowledge trivia quiz challenge', usage: '.trivia' },
  { name: 'mathgame', category: 'anime', description: 'Quick-fire mental arithmetic math test', usage: '.mathgame' },
  { name: 'wordchain', category: 'anime', description: 'Start word association chain in group', usage: '.wordchain <word>' },
  { name: 'tictactoe', category: 'anime', description: 'Play classic Tic-Tac-Toe grid with @user', usage: '.tictactoe @user' },
  { name: 'hangman', category: 'anime', description: 'Guess hidden word in classic Hangman game', usage: '.hangman' },
  { name: 'rps', category: 'anime', description: 'Play Rock, Paper, Scissors against Tyler MD', usage: '.rps rock' },
  { name: 'slots', category: 'anime', description: 'Spin virtual 777 slot machine jackpot', usage: '.slots' },
  { name: 'roulette', category: 'anime', description: 'Russian roulette game of chance with revolver', usage: '.roulette' },
  { name: 'blackjack', category: 'anime', description: 'Deal virtual cards aiming for 21 points', usage: '.blackjack' },
  { name: 'scramble', category: 'anime', description: 'Unscramble mixed letters to find English word', usage: '.scramble' },
  { name: 'guessflag', category: 'anime', description: 'Identify country nation from flag emoji', usage: '.guessflag' },
  { name: 'riddleme', category: 'anime', description: 'Get ancient folklore mystery riddle', usage: '.riddleme' },
  { name: 'roast', category: 'anime', description: 'Drop sharp comedic burn on @user', usage: '.roast @user' },

  // -------------------------------------------------------------
  // 10. UTILITIES, LOOKUP & CONVERTERS (35 COMMANDS)
  // -------------------------------------------------------------
  { name: 'math', category: 'tools', description: 'Compute mathematical expressions accurately', usage: '.math 2^8 + sqrt(144)' },
  { name: 'readqr', category: 'tools', description: 'Decode and read URL text from quoted QR image', usage: '.readqr' },
  { name: 'shorten', category: 'tools', description: 'Shorten long URL into tiny clean link', usage: '.shorten <url>' },
  { name: 'unshorten', category: 'tools', description: 'Expand shortened URL to inspect target domain', usage: '.unshorten <short_url>' },
  { name: 'forecast', category: 'tools', description: 'Detailed 5-day weather meteorology forecast', usage: '.forecast <city>' },
  { name: 'clock', category: 'tools', description: 'Display world clocks across major capitals', usage: '.clock' },
  { name: 'convert', category: 'tools', description: 'Convert metric units (km to miles, kg to lbs)', usage: '.convert 100 km to miles' },
  { name: 'currency', category: 'tools', description: 'Live foreign currency exchange rates', usage: '.currency 100 USD to EUR' },
  { name: 'crypto', category: 'tools', description: 'Check real-time Bitcoin & cryptocurrency prices', usage: '.crypto btc' },
  { name: 'btc', category: 'tools', description: 'Live Bitcoin USD value, 24h volume & trends', usage: '.btc' },
  { name: 'eth', category: 'tools', description: 'Live Ethereum price and gas tracker', usage: '.eth' },
  { name: 'whois', category: 'tools', description: 'Lookup domain registration and DNS registrar', usage: '.whois google.com' },
  { name: 'ipinfo', category: 'tools', description: 'Inspect IP geolocation, ISP and country code', usage: '.ipinfo 8.8.8.8' },
  { name: 'dnslookup', category: 'tools', description: 'Query A, CNAME, MX and TXT DNS records', usage: '.dnslookup cloudflare.com' },
  { name: 'speedtest', category: 'tools', description: 'Benchmark server bandwidth download/upload', usage: '.speedtest' },
  { name: 'github', category: 'tools', description: 'Search GitHub repositories, stars & forks', usage: '.github <query>' },
  { name: 'gituser', category: 'tools', description: 'Inspect GitHub developer profile & repos count', usage: '.gituser <username>' },
  { name: 'npm', category: 'tools', description: 'Search Node.js NPM package registry info', usage: '.npm <package_name>' },
  { name: 'pypi', category: 'tools', description: 'Search Python PyPI packages and versions', usage: '.pypi <package_name>' },
  { name: 'wikipedia', category: 'tools', description: 'Search Wikipedia encyclopedic articles', usage: '.wikipedia <query>', aliases: ['wiki'] },
  { name: 'google', category: 'tools', description: 'Google search top snippet results', usage: '.google <query>' },
  { name: 'duckduckgo', category: 'tools', description: 'Private privacy-first web search', usage: '.duckduckgo <query>' },
  { name: 'translate2', category: 'tools', description: 'Multi-lingual translation engine', usage: '.translate2 <lang> <text>' },
  { name: 'base64enc', category: 'tools', description: 'Encode plain text string into Base64 format', usage: '.base64enc <text>' },
  { name: 'base64dec', category: 'tools', description: 'Decode Base64 string back into plain text', usage: '.base64dec <base64_str>' },
  { name: 'hash', category: 'tools', description: 'Generate cryptographic hash signature', usage: '.hash <algorithm> <text>' },
  { name: 'md5', category: 'tools', description: 'Calculate MD5 checksum hash of text', usage: '.md5 <text>' },
  { name: 'sha256', category: 'tools', description: 'Calculate SHA-256 secure hash string', usage: '.sha256 <text>' },
  { name: 'urlencode', category: 'tools', description: 'Encode string for URL query parameters', usage: '.urlencode <text>' },
  { name: 'urldecode', category: 'tools', description: 'Decode percent-encoded URL string', usage: '.urldecode <encoded_str>' },
  { name: 'hexrgb', category: 'tools', description: 'Convert Hex color code to RGB values', usage: '.hexrgb #38bdf8' },
  { name: 'morse', category: 'tools', description: 'Encode text message into Morse code dots/dashes', usage: '.morse <text>' },
  { name: 'binaryenc', category: 'tools', description: 'Convert text into 0s and 1s binary bits', usage: '.binaryenc <text>' },
  { name: 'binarydec', category: 'tools', description: 'Convert binary bits back to readable text', usage: '.binarydec 01001000' },
  { name: 'tempmail', category: 'tools', description: 'Generate temporary disposable email inbox', usage: '.tempmail' },

  // -------------------------------------------------------------
  // 11. SUPER OWNER & SYSTEM CONTROL (30 COMMANDS)
  // -------------------------------------------------------------
  { name: 'shutdown', category: 'owner', description: 'Gracefully save credentials and stop bot process', usage: '.shutdown', ownerOnly: true },
  { name: 'restart', category: 'owner', description: 'Perform full reboot of Tyler MD Baileys client', usage: '.restart', ownerOnly: true },
  { name: 'block', category: 'owner', description: 'Block target phone number on WhatsApp', usage: '.block @user', ownerOnly: true },
  { name: 'unblock', category: 'owner', description: 'Unblock phone number on WhatsApp', usage: '.unblock @user', ownerOnly: true },
  { name: 'blocklist', category: 'owner', description: 'Inspect all blocked WhatsApp contacts', usage: '.blocklist', ownerOnly: true },
  { name: 'unblockall', category: 'owner', description: 'Unblock all blocked numbers on WhatsApp', usage: '.unblockall', ownerOnly: true },
  { name: 'setbotname', category: 'owner', description: 'Change display name of Tyler MD', usage: '.setbotname <name>', ownerOnly: true },
  { name: 'setbio', category: 'owner', description: 'Update WhatsApp account status bio', usage: '.setbio <bio_text>', ownerOnly: true },
  { name: 'setppbot', category: 'owner', description: 'Set bot profile picture from quoted photo', usage: '.setppbot', ownerOnly: true },
  { name: 'delppbot', category: 'owner', description: 'Remove bot profile picture', usage: '.delppbot', ownerOnly: true },
  { name: 'backup', category: 'owner', description: 'Generate encrypted backup of session credentials', usage: '.backup', ownerOnly: true },
  { name: 'restore', category: 'owner', description: 'Restore session credentials from backup', usage: '.restore <key>', ownerOnly: true },
  { name: 'eval', category: 'owner', description: 'Execute JavaScript code directly in Node runtime', usage: '.eval <code>', ownerOnly: true },
  { name: 'exec', category: 'owner', description: 'Execute bash shell command on host container', usage: '.exec <cmd>', ownerOnly: true },
  { name: 'shell', category: 'owner', description: 'Run terminal command with stdout pipe', usage: '.shell <cmd>', ownerOnly: true },
  { name: 'viewsession', category: 'owner', description: 'Inspect active session tokens and registration state', usage: '.viewsession', ownerOnly: true },
  { name: 'clearsession', category: 'owner', description: 'Wipe session cache directory', usage: '.clearsession', ownerOnly: true },
  { name: 'exportsession', category: 'owner', description: 'Export Base64 session string for Heroku/VPS', usage: '.exportsession', ownerOnly: true },
  { name: 'serverreboot', category: 'owner', description: 'Trigger restart of Linux host daemon', usage: '.serverreboot', ownerOnly: true },
  { name: 'reloadplugins', category: 'owner', description: 'Hot reload all 350+ plugins from disk', usage: '.reloadplugins', ownerOnly: true },
  { name: 'maintenance', category: 'owner', description: 'Toggle maintenance mode notice in chats', usage: '.maintenance on/off', ownerOnly: true },
  { name: 'killprocess', category: 'owner', description: 'Terminate Node process for container reload', usage: '.killprocess', ownerOnly: true },
  { name: 'superadmin', category: 'owner', description: 'Root authorization diagnostics status', usage: '.superadmin', ownerOnly: true },
  { name: 'resetbot', category: 'owner', description: 'Factory reset bot configuration parameters', usage: '.resetbot', ownerOnly: true },
  { name: 'savecontact', category: 'owner', description: 'Save user vCard to WhatsApp address book', usage: '.savecontact @user <name>', ownerOnly: true },
  { name: 'broadcastall', category: 'owner', description: 'Mass broadcast to all private DMs & groups', usage: '.broadcastall <text>', ownerOnly: true },
  { name: 'getip', category: 'owner', description: 'Reveal server public egress IP address', usage: '.getip', ownerOnly: true },
  { name: 'flushgc', category: 'owner', description: 'Force Immediate V8 Garbage Collector cycle', usage: '.flushgc', ownerOnly: true },
  { name: 'memoryreport', category: 'owner', description: 'Print full V8 heap allocation tree', usage: '.memoryreport', ownerOnly: true },
  { name: 'auditsecurity', category: 'owner', description: 'Comprehensive security integrity audit', usage: '.auditsecurity', ownerOnly: true },
];
